apiVersion: v1
kind: Service
metadata:
  name: backend-nodejs
  namespace: suseapp
  labels:
    tier: backend
spec:
  selector:
    app: backend-nodejs
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000

