apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-suse
  namespace: hpademo
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-suse
  targetCPUUtilizationPercentage: 1
