apiVersion: v1
kind: Service
metadata:
  name: hello-suse
  namespace: hpademo
  labels:
    app: hello-suse
spec:
  selector:
    app: hello-suse
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30001
  type: NodePort
