apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: suseapp
  labels: 
    tier: db
spec:
  type: NodePort
  selector:             # indicates into which pods ClusterIP provides access
    app: adminer
  ports:
    - port: 8080          # port exposed outside ClusterIP
      targetPort: 8080    # port exposed by Pod
